conf-generator:
    container_name: proxy-conf-generator
    image: jwilder/docker-gen
    entrypoint:
        - /usr/local/bin/docker-gen
        - -notify-sighup
        - proxy
        - -watch
        - -only-exposed
        - -wait
        - 5s:30s
        - /etc/docker-gen/templates/nginx.tmpl
        - /etc/nginx/conf.d/default.conf
    volumes:
        - proxy-certs:/etc/nginx/certs
        - proxy-conf:/etc/nginx/conf.d
        - proxy-vhost:/etc/nginx/vhost.d
        - proxy-webroot:/usr/share/nginx/html
        - ./resources/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
        - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

proxy:
    container_name: proxy
    image: nginx
    ports:
        - "80:80"
        - "443:443"
    restart: always
    volumes:
        - proxy-certs:/etc/nginx/certs
        - proxy-conf:/etc/nginx/conf.d
        - proxy-vhost:/etc/nginx/vhost.d
        - proxy-webroot:/usr/share/nginx/html

cert-generator:
    container_name: proxy-cert-generator
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
        - NGINX_DOCKER_GEN_CONTAINER=generator
        - ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory # This makes us use Let's Encrypt staging
    volumes:
        - proxy-certs:/etc/nginx/certs
        - proxy-vhost:/etc/nginx/vhost.d
        - proxy-webroot:/usr/share/nginx/html
        - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
