#!/bin/bash

GOGS_DOMAIN="git.$DOMAIN"
JENKINS_DOMAIN="ci.$DOMAIN"
REGISTRY_DOMAIN="docker.$DOMAIN"
TORAN_DOMAIN="toran.$DOMAIN"

SSL_DOMAINS="$DOMAIN,$GOGS_DOMAIN,$JENKINS_DOMAIN,$REGISTRY_DOMAIN,$TORAN_DOMAIN"
SSL_EMAIL="letsencrypt@davidjbingham.co.uk"
