dist_sync_mode: lazy
git_prefix: git@davidjbingham.co.uk
git_path: /data/toran-proxy/mirrors
license: null
license_personal: true
packagist_sync: proxy
public_packages: {}
public_repositories: {}
repositories: {}
