security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 13

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    # Passwords hashed by:
                    # php -r "echo password_hash('password', PASSWORD_BCRYPT, ['cost' => 13]) . PHP_EOL;"
                    admin:
                        password: $2y$13$C25KvW7Zj8m.iMh7R6bgbOE/TC.4KBcYIts9tE52QXkV.GTam.GR2
                        roles: [ ROLE_ADMIN ]

    firewalls:
        secured_area:
            pattern: ^/
            http_basic:
                realm: "Toran proxy access"

    access_control:
        - { path: ^/, roles: ROLE_ADMIN } # restrict website access to admin only
        - { path: ^/repo, roles: IS_AUTHENTICATED_ANONYMOUSLY } # allow repo access to unauthenticated users
