registry:
    container_name: registry
    image: registry:2
    environment:
        - REGISTRY_HTTP_TLS_CERTIFICATE="/etc/nginx/certs/${REGISTRY_DOMAIN}.crt"
        - REGISTRY_HTTP_TLS_KEY="/etc/nginx/certs/${REGISTRY_DOMAIN}.key"
        - REGISTRY_HTTP_SECRET="my_registry_secret_1343y57134134141ml9"
    ports:
        - "5000:5000"
    restart: always
    volumes:
        - registry-data:/var/lib/registry
        - proxy-certs:/etc/nginx/certs:ro

web:
    container_name: registry-web
    image: nginx
    environment:
        - VIRTUAL_HOST="${REGISTRY_DOMAIN}"
        - LETSENCRYPT_HOST="${REGISTRY_DOMAIN}"
        - LETSENCRYPT_EMAIL="${LETSENCRYPT_EMAIL}"
    expose:
        - "80"
        - "443"
