toran:
    container_name: toran
    image: cedvan/toran-proxy
    environment:
        - TORAN_CRON_TIMER=minutes
        - VIRTUAL_HOST="${TORAN_DOMAIN}"
        - VIRTUAL_PORT=8080
        - LETSENCRYPT_HOST="${TORAN_DOMAIN}"
        - LETSENCRYPT_EMAIL="${LETSENCRYPT_EMAIL}"
    restart: always
    volumes:
        - toran-data:/data
